version: '3'

services:
  metasploitable:
    image: tleemcjr/metasploitable2
    container_name: metasploitable
    command: sh -c "/bin/services.sh && sleep 10000"
    networks:
      - scanning_network

  vulnmapai:
    container_name: vulnmapai
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - "/dev/net/tun:/dev/net/tun"
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash -c "sleep 20 && python /app/main.py"
    networks:
      - scanning_network
    volumes:
      - ./:/app/

networks:
  scanning_network:
    driver: bridge
