name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      shell: bash
      run: |
        # fail if any bash syntax error
        set -eEuo pipefail

        export DOCKER_BUILDKIT=1

        # with the new target, test the pytest works
        docker build -f build/final_image/Dockerfile --target test -t test-vulmap-works:latest .
        docker rmi test-vulmap-works:latest

        # build the image aswell, in case more steps arise
        docker build -f build/final_image/Dockerfile -t vulnmapai:latest .
